# Generated by Django 4.0.5 on 2022-06-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_modelone_modeltwo_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='554d47897a', editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
