# Generated by Django 4.0.5 on 2022-06-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='82031d2f82', editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
