# Generated by Django 4.0.5 on 2022-06-19 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddmapp', '0002_crrr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crrr',
        ),
    ]
