# Generated by Django 4.0.5 on 2022-06-26 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fake_app', '0004_see_sesee_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='See',
        ),
        migrations.DeleteModel(
            name='Sesee',
        ),
    ]
